# Generated by Django 3.1.6 on 2021-03-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_appointment_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.CharField(choices=[('rita', 'rita'), ('sita', 'sita'), ('gita', 'gita')], default='not_verified', max_length=120),
        ),
    ]
