# Generated by Django 3.1.6 on 2021-03-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_appointment_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='endtime',
            field=models.TimeField(null=True),
        ),
    ]
