# Generated by Django 3.1.6 on 2021-03-20 12:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_appointment_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='List',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('30', 'haircut'), ('90', 'hair color'), ('89', 'facial'), ('45', 'oil massage'), ('15', 'threading'), ('29', 'mehendi'), ('40', 'waxing'), ('28', 'nailcare'), ('60', 'makeup')], max_length=26),
        ),
    ]
